{
  "uptime": [
    {
      "created_at": "2022-04-17T03:21:59",
      "updated_at": "2022-04-17T03:21:59",
      "html_url": "https://github.com/pulibrary/uptime/issues/393",
      "number": 393,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "closed",
      "title": "ðŸ›‘ Confluence is down",
      "user_name": "Francis Kayiwa",
      "comments": [
        {
          "user_name": "Francis Kayiwa",
          "updated_at": "2022-04-17T04:20:43",
          "html_url": "https://github.com/pulibrary/uptime/issues/393#issuecomment-1100800476",
          "body": "**Resolved:** Confluence is back up in [`96c067d`](https://github.com/pulibrary/uptime/commit/96c067dbd247cd673aafc4e742a2e8d0b179ec57\n)."
        }
      ],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2022-04-17T03:21:59",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2022-04-17T03:21:59",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2022-04-17T03:22:00",
          "type": "locked"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2022-04-17T04:20:44",
          "type": "closed"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    }
  ],
  "__meta__": {
    "issue_count": 1,
    "created_count": 1,
    "today": "2022-04-17T22:00:04",
    "yesterday": "2022-04-16T22:00:04"
  }
}