{
  "princeton_ansible": [
    {
      "created_at": "2021-01-12T18:23:37",
      "updated_at": "2021-01-12T18:23:37",
      "html_url": "https://github.com/pulibrary/princeton_ansible/issues/2065",
      "number": 2065,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/princeton_ansible",
      "repository_name": "princeton_ansible",
      "state": "open",
      "title": "Library statistics machine",
      "user_name": "carolyncole",
      "comments": [],
      "events": [],
      "pr_html_url": null,
      "action": "updated"
    }
  ],
  "pul-the-hard-way": [
    {
      "created_at": "2021-01-14T17:15:48",
      "updated_at": "2021-01-14T17:15:48",
      "html_url": "https://github.com/pulibrary/pul-the-hard-way/pull/67",
      "number": 67,
      "pull_request_html_url": "https://github.com/pulibrary/pul-the-hard-way/pull/67",
      "repository_html_url": "https://github.com/pulibrary/pul-the-hard-way",
      "repository_name": "pul-the-hard-way",
      "state": "closed",
      "title": "add documentation for generic signing request",
      "user_name": "Francis Kayiwa",
      "comments": [],
      "events": [
        {
          "actor_name": null,
          "created_at": "2021-01-16T02:03:54",
          "type": "head_ref_deleted"
        }
      ],
      "pr_html_url": "https://github.com/pulibrary/pul-the-hard-way/pull/67",
      "action": "pull_request_closed"
    }
  ],
  "uptime": [
    {
      "created_at": "2021-01-16T02:59:21",
      "updated_at": "2021-01-16T02:59:21",
      "html_url": "https://github.com/pulibrary/uptime/issues/59",
      "number": 59,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "closed",
      "title": "ðŸ›‘ Confluence is down",
      "user_name": "Francis Kayiwa",
      "comments": [
        {
          "user_name": "Francis Kayiwa",
          "updated_at": "2021-01-16T04:58:31",
          "html_url": "https://github.com/pulibrary/uptime/issues/59#issuecomment-761413863",
          "body": "**Resolved:** Confluence is back up in [`2de5e9c`](https://github.com/pulibrary/uptime/commit/2de5e9cb7193ca14437e70439ae43b0d529d2160\n)."
        }
      ],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-16T02:59:21",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-16T02:59:21",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-16T02:59:22",
          "type": "locked"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-16T04:58:32",
          "type": "closed"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    }
  ],
  "__meta__": {
    "issue_count": 3,
    "created_count": 1,
    "pull_request_closed_count": 1,
    "updated_count": 1,
    "today": "2021-01-16T22:00:04",
    "yesterday": "2021-01-15T22:00:04"
  }
}