{
  "uptime": [
    {
      "created_at": "2020-12-20T04:01:09",
      "updated_at": "2020-12-20T04:01:09",
      "html_url": "https://github.com/pulibrary/uptime/issues/37",
      "number": 37,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "closed",
      "title": "ðŸ›‘ Confluence is down",
      "user_name": "Francis Kayiwa",
      "comments": [
        {
          "user_name": "Francis Kayiwa",
          "updated_at": "2020-12-20T04:30:26",
          "html_url": "https://github.com/pulibrary/uptime/issues/37#issuecomment-748561508",
          "body": "**Resolved:** Confluence is back up in [`180133f`](https://github.com/pulibrary/uptime/commit/180133fdbddfe4795b75d82d6f7bb2843ed03bcb\n)."
        }
      ],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T04:01:09",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T04:01:09",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T04:01:10",
          "type": "locked"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T04:30:27",
          "type": "closed"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    },
    {
      "created_at": "2020-12-20T20:44:23",
      "updated_at": "2020-12-20T20:44:23",
      "html_url": "https://github.com/pulibrary/uptime/issues/38",
      "number": 38,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "closed",
      "title": "ðŸ›‘ OAR is down",
      "user_name": "Francis Kayiwa",
      "comments": [
        {
          "user_name": "Francis Kayiwa",
          "updated_at": "2020-12-20T20:51:46",
          "html_url": "https://github.com/pulibrary/uptime/issues/38#issuecomment-748669272",
          "body": "**Resolved:** OAR is back up in [`a2c98f9`](https://github.com/pulibrary/uptime/commit/a2c98f9a7883574fc62cbaf89af1b089243432f0\n)."
        }
      ],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T20:44:23",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T20:44:23",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T20:44:24",
          "type": "locked"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2020-12-20T20:51:47",
          "type": "closed"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    }
  ],
  "__meta__": {
    "issue_count": 2,
    "created_count": 2,
    "today": "2020-12-20T22:00:07",
    "yesterday": "2020-12-19T22:00:07"
  }
}